# which benchmarks to run
benchmarks = '../../benchmarks/**/*.bril'
# how to extract the performance metric from stderr
extract = 'total_dyn_inst: (\d+)'

[runs.baseline]
pipeline = [
  "bril2json",
  "brili -p {args}",
]

[runs.global_dce]
pipeline = [
  "bril2json",
  "python3 global_dce.py",
  "brili -p {args}",
]

[runs.local_dce]
pipeline = [
  "bril2json",
  "python3 local_dce.py",
  "brili -p {args}",
]

[runs.local_value_numbering]
pipeline = [
  "bril2json",
  "python3 local_value_numbering.py",
  "brili -p {args}",
]

[runs.lvn_then_local_dce]
pipeline = [
  "bril2json",
  "python3 local_value_numbering.py",
  "python3 local_dce.py",
  "brili -p {args}",
]

[runs.global_dce_then_lvn]
pipeline = [
  "bril2json",
  "python3 global_dce.py",
  "python3 local_value_numbering.py",
  "brili -p {args}",
]

[runs.all_passes]
pipeline = [
  "bril2json",
  "python3 global_dce.py",
  "python3 local_value_numbering.py",
  "python3 local_dce.py",
  "brili -p {args}",
]
